import { getUserProfile, updateProfile, changePassword, updateRole, assignUserToGarage, getAllUsers, getAllManagers, getMechanicsByGarage, changeMechanicStatus, getMechanicSkills, setMechanicSkills, assignOwnerToGarage } from "../services/userService.js";
import { registerUser } from "../services/authService.js";
import { fetchMyNotifications, savePushToken, markAsRead, deleteNotification, deleteAllNotifications } from "../services/notificationService.js";
import { getSuperAdminStats, getSuperAdminAnalytics } from "../services/dashboardService.js";
import { sendTemporaryPasswordEmail } from "../services/emailService.js";
import asyncHandler from "../utils/asyncHandler.js";
import crypto from "crypto";

export const getProfile = asyncHandler(async (req, res) => {
  const userProfile = await getUserProfile(req.user.id);
  res.json({
    user: {
      id: userProfile.UserID,
      fullName: userProfile.FullName,
      email: userProfile.Email,
      phone: userProfile.PhoneNumber,
      role: userProfile.Role,
      status: userProfile.Status,
      GarageID: userProfile.GarageID,
      GarageName: userProfile.GarageName
    }
  });
});

export const editProfile = asyncHandler(async (req, res) => {
  await updateProfile(req.user.id, req.body);
  res.json({ message: "Profile updated successfully" });
});

export const editPassword = asyncHandler(async (req, res) => {
  const { oldPassword, newPassword } = req.body;
  await changePassword(req.user.id, oldPassword, newPassword);
  res.json({ message: "Password updated successfully" });
});

export const setUserRole = asyncHandler(async (req, res) => {
  const { userId } = req.params;
  const { role } = req.body;
  await updateRole(userId, role);
  res.json({ message: `User role updated to ${role}` });
});

export const assignToGarage = asyncHandler(async (req, res) => {
  const { userId } = req.params;
  const { garageId } = req.body;
  await assignUserToGarage(userId, garageId, req.user);
  res.json({ message: "User assigned successfully" });
});

export const getNotifications = asyncHandler(async (req, res) => {
  const notifications = await fetchMyNotifications(req.user.id);
  res.json(notifications);
});

export const readNotification = asyncHandler(async (req, res) => {
  await markAsRead(req.params.id, req.user.id);
  res.json({ message: "Notification marked as read" });
});

export const removeNotification = asyncHandler(async (req, res) => {
  await deleteNotification(req.params.id, req.user.id);
  res.json({ message: "Notification deleted" });
});

export const removeAllNotifications = asyncHandler(async (req, res) => {
  await deleteAllNotifications(req.user.id);
  res.json({ message: "All notifications deleted" });
});

export const registerToken = asyncHandler(async (req, res) => {
  const { token, deviceType } = req.body;
  await savePushToken(req.user.id, token, deviceType);
  res.json({ message: "Registration token saved" });
});

export const getAdminDashboard = asyncHandler(async (req, res) => {
  const stats = await getSuperAdminStats();
  res.json(stats);
});

export const getAdminAnalytics = asyncHandler(async (req, res) => {
  const analytics = await getSuperAdminAnalytics();
  res.json(analytics);
});

export const getUsers = asyncHandler(async (req, res) => {
  const users = await getAllUsers();
  res.json(users);
});

export const getManagers = asyncHandler(async (req, res) => {
  const managers = await getAllManagers();
  res.json(managers);
});

export const createManager = asyncHandler(async (req, res) => {
  const { fullName, email, phone } = req.body;
  const password = crypto.randomBytes(4).toString('hex'); // 8 characters

  const result = await registerUser({
    fullName,
    email,
    phone,
    password,
    role: "GarageManager"
  });

  await sendTemporaryPasswordEmail(email, fullName, password);

  res.status(201).json({ message: "Manager created successfully", userId: result.userId });
});

export const createOwner = asyncHandler(async (req, res) => {
  const { fullName, email, phone } = req.body;
  const password = crypto.randomBytes(4).toString('hex'); // 8 characters

  const result = await registerUser({
    fullName,
    email,
    phone,
    password,
    role: "GarageOwner"
  });

  await sendTemporaryPasswordEmail(email, fullName, password);

  res.status(201).json({ message: "Garage Owner created successfully", userId: result.userId });
});

export const getGarageMechanics = asyncHandler(async (req, res) => {
  const { garageId } = req.params;
  const mechanics = await getMechanicsByGarage(garageId);
  res.json(mechanics);
});

export const createMechanic = asyncHandler(async (req, res) => {
  const { garageId } = req.params;
  let { fullName, email, phone, password, skills } = req.body;

  let isAutoGenerated = false;
  if (!password || password.trim() === '') {
    password = crypto.randomBytes(4).toString('hex'); // 8 characters
    isAutoGenerated = true;
  }

  // 1. Create the user with role 'Mechanic'
  const result = await registerUser({
    fullName,
    email,
    phone,
    password,
    role: "Mechanic"
  });

  // 2. Assign to garage
  await assignUserToGarage(result.userId, garageId, req.user);

  // 3. Save skills if provided at registration time
  if (Array.isArray(skills) && skills.length > 0) {
    await setMechanicSkills(garageId, result.userId, skills, req.user);
  }

  // 4. Send email if auto generated
  if (isAutoGenerated) {
    await sendTemporaryPasswordEmail(email, fullName, password);
  }

  res.status(201).json({ message: "Mechanic created and assigned successfully", userId: result.userId });
});

export const updateMechanicStatus = asyncHandler(async (req, res) => {
  const { garageId, mechanicId } = req.params;
  const { status } = req.body;

  await changeMechanicStatus(garageId, mechanicId, status, req.user);
  res.json({ message: `Mechanic status updated to ${status}` });
});

export const getMechanicSkillsHandler = asyncHandler(async (req, res) => {
  const { mechanicId } = req.params;
  const skills = await getMechanicSkills(mechanicId);
  res.json(skills);
});

export const updateMechanicSkillsHandler = asyncHandler(async (req, res) => {
  const { garageId, mechanicId } = req.params;
  const { skills } = req.body;
  await setMechanicSkills(garageId, mechanicId, skills, req.user);
  res.json({ message: "Skills updated successfully" });
});

export const assignOwnerToGarageHandler = asyncHandler(async (req, res) => {
  const { garageId } = req.params;
  const { ownerId } = req.body; // null to unassign
  await assignOwnerToGarage(garageId, ownerId ?? null);
  res.json({ message: ownerId ? "Owner assigned successfully" : "Owner unassigned successfully" });
});
